- name: build
  tasks:
    - taskfile js
    - taskfile html

- name: package
  tasks:
    - mkdir -p package
    - - electron-packager . koikoi --all --icon "/media/birdhouse.svg" --out package/

- name: js
  tasks:
    - webpack

- name: html
  tasks:
    - mkdir -p app
    - - htmlmin -o app/index.html src/index.html

- name: clean
  tasks:
    - rimraf app/
    - rimraf node_modules/
